// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Lets `prisma migrate reset` repopulate the database in one step.
    seed: "node prisma/seed.js",
  },
  datasource: {
    // The CLI (migrate, db push, studio) connects DIRECTLY, not through the
    // Neon pooler: pooled connections cannot hold the advisory lock that
    // `migrate` takes, which fails with P1002. The app itself still uses the
    // pooled DATABASE_URL via the adapter in src/lib/prisma.js.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
