@BASE_URL = http://localhost:8000


// Reserve
// CARS
### GET reserve
GET {{BASE_URL}}/reserve/cars   

### POST reserve
POST {{BASE_URL}}/reserve/cars   

### PATCH reserve
PATCH  {{BASE_URL}}/reserve/carId  

// ROOMS
### GET reserve
GET {{BASE_URL}}/reserve/rooms   

### POST reserve
POST {{BASE_URL}}/reserve/rooms  

### PATCH reserve
PATCH  {{BASE_URL}}/reserve/rooms/roomId
